/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedAssinaturaRouteImport } from './routes/_authenticated/assinatura'
import { Route as AuthenticatedAssistenteRouteImport } from './routes/_authenticated/assistente'
import { Route as AuthenticatedComissoesRouteImport } from './routes/_authenticated/comissoes'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPixAdminRouteImport } from './routes/_authenticated/pix-admin'
import { Route as AuthenticatedServicosRouteImport } from './routes/_authenticated/servicos'
import { Route as AgendarSlugRouteImport } from './routes/agendar.$slug'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated/clientes/index'
import { Route as AuthenticatedClientesIdRouteImport } from './routes/_authenticated/clientes/$id'
import { Route as ApiPublicWebhooksMercadopagoRouteImport } from './routes/api/public/webhooks/mercadopago'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssinaturaRoute = AuthenticatedAssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistenteRoute = AuthenticatedAssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComissoesRoute = AuthenticatedComissoesRouteImport.update({
  id: '/comissoes',
  path: '/comissoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPixAdminRoute = AuthenticatedPixAdminRouteImport.update({
  id: '/pix-admin',
  path: '/pix-admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicosRoute = AuthenticatedServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AgendarSlugRoute = AgendarSlugRouteImport.update({
  id: '/agendar/$slug',
  path: '/agendar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesIdRoute = AuthenticatedClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicWebhooksMercadopagoRoute =
  ApiPublicWebhooksMercadopagoRouteImport.update({
    id: '/api/public/webhooks/mercadopago',
    path: '/api/public/webhooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/assistente': typeof AuthenticatedAssistenteRoute
  '/comissoes': typeof AuthenticatedComissoesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pix-admin': typeof AuthenticatedPixAdminRoute
  '/servicos': typeof AuthenticatedServicosRoute
  '/agendar/$slug': typeof AgendarSlugRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/clientes/': typeof AuthenticatedClientesIndexRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/assistente': typeof AuthenticatedAssistenteRoute
  '/comissoes': typeof AuthenticatedComissoesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pix-admin': typeof AuthenticatedPixAdminRoute
  '/servicos': typeof AuthenticatedServicosRoute
  '/agendar/$slug': typeof AgendarSlugRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/assinatura': typeof AuthenticatedAssinaturaRoute
  '/_authenticated/assistente': typeof AuthenticatedAssistenteRoute
  '/_authenticated/comissoes': typeof AuthenticatedComissoesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/pix-admin': typeof AuthenticatedPixAdminRoute
  '/_authenticated/servicos': typeof AuthenticatedServicosRoute
  '/agendar/$slug': typeof AgendarSlugRoute
  '/_authenticated/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agenda'
    | '/assinatura'
    | '/assistente'
    | '/comissoes'
    | '/configuracoes'
    | '/crm'
    | '/dashboard'
    | '/equipe'
    | '/estoque'
    | '/financeiro'
    | '/onboarding'
    | '/pix-admin'
    | '/servicos'
    | '/agendar/$slug'
    | '/clientes/$id'
    | '/clientes/'
    | '/api/public/webhooks/mercadopago'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agenda'
    | '/assinatura'
    | '/assistente'
    | '/comissoes'
    | '/configuracoes'
    | '/crm'
    | '/dashboard'
    | '/equipe'
    | '/estoque'
    | '/financeiro'
    | '/onboarding'
    | '/pix-admin'
    | '/servicos'
    | '/agendar/$slug'
    | '/clientes/$id'
    | '/clientes'
    | '/api/public/webhooks/mercadopago'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agenda'
    | '/_authenticated/assinatura'
    | '/_authenticated/assistente'
    | '/_authenticated/comissoes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/equipe'
    | '/_authenticated/estoque'
    | '/_authenticated/financeiro'
    | '/_authenticated/onboarding'
    | '/_authenticated/pix-admin'
    | '/_authenticated/servicos'
    | '/agendar/$slug'
    | '/_authenticated/clientes/$id'
    | '/_authenticated/clientes/'
    | '/api/public/webhooks/mercadopago'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AgendarSlugRoute: typeof AgendarSlugRoute
  ApiPublicWebhooksMercadopagoRoute: typeof ApiPublicWebhooksMercadopagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assinatura': {
      id: '/_authenticated/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AuthenticatedAssinaturaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistente': {
      id: '/_authenticated/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AuthenticatedAssistenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comissoes': {
      id: '/_authenticated/comissoes'
      path: '/comissoes'
      fullPath: '/comissoes'
      preLoaderRoute: typeof AuthenticatedComissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pix-admin': {
      id: '/_authenticated/pix-admin'
      path: '/pix-admin'
      fullPath: '/pix-admin'
      preLoaderRoute: typeof AuthenticatedPixAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/servicos': {
      id: '/_authenticated/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof AuthenticatedServicosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/agendar/$slug': {
      id: '/agendar/$slug'
      path: '/agendar/$slug'
      fullPath: '/agendar/$slug'
      preLoaderRoute: typeof AgendarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/$id': {
      id: '/_authenticated/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/mercadopago': {
      id: '/api/public/webhooks/mercadopago'
      path: '/api/public/webhooks/mercadopago'
      fullPath: '/api/public/webhooks/mercadopago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedAssinaturaRoute: typeof AuthenticatedAssinaturaRoute
  AuthenticatedAssistenteRoute: typeof AuthenticatedAssistenteRoute
  AuthenticatedComissoesRoute: typeof AuthenticatedComissoesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPixAdminRoute: typeof AuthenticatedPixAdminRoute
  AuthenticatedServicosRoute: typeof AuthenticatedServicosRoute
  AuthenticatedClientesIdRoute: typeof AuthenticatedClientesIdRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedAssinaturaRoute: AuthenticatedAssinaturaRoute,
  AuthenticatedAssistenteRoute: AuthenticatedAssistenteRoute,
  AuthenticatedComissoesRoute: AuthenticatedComissoesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPixAdminRoute: AuthenticatedPixAdminRoute,
  AuthenticatedServicosRoute: AuthenticatedServicosRoute,
  AuthenticatedClientesIdRoute: AuthenticatedClientesIdRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AgendarSlugRoute: AgendarSlugRoute,
  ApiPublicWebhooksMercadopagoRoute: ApiPublicWebhooksMercadopagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
